Program Normal
    vertex      normal.vert
    fragment    normal.frag
Program Normal2
    vertex      normal.vert
    fragment    normal2.frag
Program Basic
    vertex      basic.vert
    fragment    basic.frag
Program Blend
    vertex      normal.vert
    fragment    blend.frag
Program Blend2
    vertex      normal.vert
    fragment    blend2.frag
Program Blend3
    vertex      normal.vert
    fragment    blend3.frag    
Program BillBoarding
    vertex      billboard.vert
    fragment    normal2.frag
Program Painting
    vertex      paint.vert
    fragment    paint.frag